plugins {
    id 'com.android.application'
}

//
// Define a function to retrieve the latest git commit date.
// Attention: This functionality needs the build cache to be deactivated in gradle.properties:
//  org.gradle.configuration-cache=false
//
def gitVersionProvider = providers.exec {
    commandLine "git", "show", "--no-patch", "--format=%ai"
}
def getVersionDate = { ->
    return gitVersionProvider.standardOutput.asText.get().trim()
}

/* DEPRECATED VERSION
def getVersionDateOld = { ->
    try {
        def code = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'show', '--no-patch', '--format=%ai'
            standardOutput = code
        }
        //println code
        return code.toString().trim()
    }
    catch (ignored) {
        return -1
    }
}
*/

android {
    defaultConfig {
        applicationId "de.kromke.andreas.cameradatefolders"
        namespace "de.kromke.andreas.cameradatefolders"
        //  We could define a variable here, if we need this value more than once.
        // def varBuildDate=getVersionDate()
        //  Using the system compile time leads to not-reproducible builds, i.e. two builds with the
        //  same source code will produce slightly different binaries.
        // buildConfigField "long", "TIMESTAMP", System.currentTimeMillis() + "L"
        //  Instead, we insert the git commit time here:
        buildConfigField "String", "GIT_TIMESTAMP", "\"$getVersionDate\""
        // Instead of directly calling our function, we also could insert our variable here:
        //  buildConfigField "String", "GIT_TIMESTAMP", "\"$varBuildDate\""
        android.buildFeatures.buildConfig true
        minSdk 21
        compileSdk {
            version = release(36)
        }
        targetSdk 36
        versionCode 12
        versionName "1.5.2"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = [managePermission:"android.permission.MANAGE_EXTERNAL_STORAGE"]
    }

    buildTypes {
        release_dbg {
            minifyEnabled true /* use proguard... */
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }

        release_play {
            minifyEnabled true
            // with proguard-android.txt the Log calls will NOT BE REMOVED
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules-remove-log.pro'
            manifestPlaceholders = [managePermission:"android.permission.WRITE_EXTERNAL_STORAGE"]
            signingConfig signingConfigs.debug
        }

        debug_play {
            debuggable true
            signingConfig signingConfigs.debug
            manifestPlaceholders = [managePermission:"android.permission.WRITE_EXTERNAL_STORAGE"]
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.9.4'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.4'
    implementation 'androidx.navigation:navigation-fragment:2.9.5'
    implementation 'androidx.navigation:navigation-ui:2.9.5'

    // Fix Duplicate class
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.9.0"))
    implementation 'androidx.documentfile:documentfile:1.1.0'
}
